### ISSUE TITLE
Can a example be done showing how to run a command from the command palette

### ISSUE THREAD

**Issue by peterlouvel** [egodigital/vscode-powertools-samples#1]
Hi,

I can't figure out how to create a button to execute a command from the command palette like shown in the picture. I can get a script to show the message box etc.

![image](https://user-images.githubusercontent.com/240880/61016163-068eeb00-a3d2-11e9-9b6b-34ab547a8fe8.png)

Can someone do an example showing how to run a command palette command

Thanks

**Comment by ghost** [comment]
@peterlouvel

Open `Power Tools: Tools` >> `Code Execution` in your command palette (`CTRL + P` or `CMD + CTRL + P`) and execute

```javascript
$vs.commands.getCommands
```

You will get a complete list of all commands, which are currently available in VSCode.

You can try to search for keywords, like `power` and/or `shell`, to find out what command name to use as a [button commands](https://github.com/egodigital/vscode-powertools/wiki/Buttons#visual-studio-code-commands). The source code of [the extension](https://marketplace.visualstudio.com/items?itemName=ironmansoftware.powershellprotools) does not seem to be available, so I unfortunately cannot give you a better hint, what command IDs are used by it.

Replace escaped expressions, like `\.`, with `.`

**Comment by peterlouvel** [comment]
Hi,

Thanks for the info
I think I found the command   1103 | powershell\.showWinFormDesigner
so now I have to figure out how to get powertools button to run  that.

I added the following into settings.json  
![image](https://user-images.githubusercontent.com/240880/61094155-2df8bd00-a491-11e9-8e3f-f6e4970883ef.png)

but that didn't work  
![image](https://user-images.githubusercontent.com/240880/61094137-1c171a00-a491-11e9-99c5-43dbb7eb3a15.png)

Also tried

"command": "vscode.Powershell.showWinFormDesigner"

-----

ok no idea why   but it's working now  same code as above except is lowercase  powershell
"command": "powershell.showWinFormDesigner"

**Comment by ghost** [comment]
@peterlouvel 

You have to take the ID exactly as it is ... **command IDs are case sensitive**.
